/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Shane Vince Marcos (https://sketchfab.com/shanevmm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/aoi-319e0495feb0421886fa3687f7869b7c
title: Aoi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/aio.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.025} position={[0, -2.5,0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Bangs} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Base} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Collar} />
        <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
        <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Main_cloth} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Sleeves} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Sleeves_Cuff} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Std_Cornea_L} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Std_Cornea_R} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Std_Eye_L} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Std_Eye_Occlusion_L} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Std_Eye_Occlusion_R} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Std_Eye_R} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Std_Eyelash} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Std_Lower_Teeth} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Std_Nails} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Std_Skin_Arm} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Std_Skin_Body} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Std_Skin_Head} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Std_Skin_Leg} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Std_Tearline_L} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Std_Tearline_R} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Std_Tongue} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Std_Upper_Teeth} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Waist_Cuffs} />
        <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
        <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.stripe} />
      </group>
    </group>
  )
}

useGLTF.preload('/aio.gltf')
