/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SomeDude (https://sketchfab.com/Patyot.Suttipreecha)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/swordgirl-a173c4b5243a4a90b09c83937dcb44fa
title: SwordGirl
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  // eslint-disable-next-line no-unused-vars
  const { nodes, materials } = useGLTF('/swordgirl.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.5} position={[0.2,-2.3,1]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.03, 0, 0]} >
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_7.geometry}
              material={nodes.Object_7.material}
              skeleton={nodes.Object_7.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_8.geometry}
              material={nodes.Object_8.material}
              skeleton={nodes.Object_8.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_10.geometry}
              material={nodes.Object_10.material}
              skeleton={nodes.Object_10.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_12.geometry}
              material={nodes.Object_12.material}
              skeleton={nodes.Object_12.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_14.geometry}
              material={nodes.Object_14.material}
              skeleton={nodes.Object_14.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_16.geometry}
              material={nodes.Object_16.material}
              skeleton={nodes.Object_16.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_17.geometry}
              material={nodes.Object_17.material}
              skeleton={nodes.Object_17.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_18.geometry}
              material={nodes.Object_18.material}
              skeleton={nodes.Object_18.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_20.geometry}
              material={nodes.Object_20.material}
              skeleton={nodes.Object_20.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_22.geometry}
              material={nodes.Object_22.material}
              skeleton={nodes.Object_22.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_24.geometry}
              material={nodes.Object_24.material}
              skeleton={nodes.Object_24.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_26.geometry}
              material={nodes.Object_26.material}
              skeleton={nodes.Object_26.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_28.geometry}
              material={nodes.Object_28.material}
              skeleton={nodes.Object_28.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_30.geometry}
              material={nodes.Object_30.material}
              skeleton={nodes.Object_30.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/swordgirl.gltf')
