/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zeena (https://sketchfab.com/zhangyujie258)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/scifi-barral-dbe53d8f75ca471fa8d9171d9e7b3242
title: Scifi-barral
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/barral.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.0075} position={[5,-2.4,-0.75]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.pCylinder7_lambert1_0.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/barral.gltf')
