/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: willc3d (https://sketchfab.com/willc3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/old-gas-pump-a91aa1281e0840f29bc4404b2bc1cd13
title: Old Gas Pump
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gasPump.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.5]} scale={0.075} position={[-1.5, -2.4, -2]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.scene_material} />
      </group>
    </group>
  )
}

useGLTF.preload('/gasPump.gltf')
